# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='img_name',
            field=models.CharField(default='img.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
